name: Scrape Manga Updates

on:
  schedule:
    # Runs every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run ManhwaClan scraper
        run: python scraper.py

      - name: Run ManhwaBTT scraper
        run: python manga_scraper.py

      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions Scraper'
          git config --global user.email 'actions@github.com'
          git add manhwa_db.json manga_top_all.json || exit 0
          git diff --staged --quiet || (git commit -m "Update manga data" && git push)

      - name: Trigger Render redeploy
        if: success()
        run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"