name: Scrape Manga Updates

on:
  schedule:
    # Runs every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run ManhwaClan scraper
        run: python scraper.py

      - name: Run ManhwaBTT scraper
        run: python manga_scraper.py

      - name: Set up PAT for pushing
        run: |
          git config --global user.name "GitHub Actions Scraper"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://blank7k:${{ secrets.PAT_TOKEN }}@github.com/blank7k/manhwa-companion.git

      - name: Commit and push if changed
        run: |
          git add manhwa_db.json manga_top_all.json
          git diff --staged --quiet || (git commit -m "Update manga data" && git push)
