name: Scrape Manga Updates

on:
  schedule:
    # Runs every hour
    - cron: "0 * * * *"
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # or your preferred version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 # Add any other scraping dependencies

      - name: Run scraper
        run: python manga_scraper.py # Or the name of your main scraper script

      - name: Commit and push if changed
        run: |
          git config --global user.name "GitHub Actions Scraper"
          git config --global user.email "actions@github.com"
          git add manhwa_db.json manga_top_all.json # Add all JSON files that are updated
          git diff --staged --quiet || (git commit -m "Update manga data" && git push) 